/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundo.redes.sistemas.tienda_zapatos_matutino;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin
 */
public class RelsB extends javax.swing.JFrame {

    /**
     * Creates new form RelsB
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public RelsB() {
        initComponents();
        jTablaDetalle.setModel(modelo);
        //agregar columnas
        modelo.addColumn("MARCA");
        modelo.addColumn("GENERO");
        modelo.addColumn("TALLA");
        modelo.addColumn("COLOR");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO UNITARIO");
        modelo.addColumn("PRECIO TOTAL");

    }

    public void promocionHombreNike() {
        double descuento = 0, preciounit, preciototal;
        int cantidadCalzados;
        //seleccionada la marca
        if (jMarca.getSelectedIndex() == 1) {
            if (jRHombre.isSelected() == true) {
                //seleccionada las tallas
                if (jCTalla.getSelectedIndex() >= 5) {
                    descuento = 0.05;
                } else if (jCTalla.getSelectedIndex() == 6) {
                    descuento = 0.07;
                } else if (jCTalla.getSelectedIndex() == 7) {
                    descuento = 0.09;
                } else if (jCTalla.getSelectedIndex() == 8) {
                    descuento = 0.11;
                } else if (jCTalla.getSelectedIndex() == 9) {
                    descuento = 0.13;
                }

            }
            cantidadCalzados = (int) jCantidad.getValue();
            preciounit = Double.parseDouble(jTextPrecioU.getText());
            preciototal = (cantidadCalzados * preciounit) - ((cantidadCalzados * preciounit) * descuento);
            jTextPrecioTotal.setText(String.valueOf(preciototal));

        } else {
            JOptionPane.showMessageDialog(null, "Talla incorrcta", "ERROR", JOptionPane.ERROR_MESSAGE);
            jCTalla.setSelectedIndex(0);
            jTextPrecioTotal.setText("");
        }

    }

    public void promocionMujerNike() {
        double descuento = 0, preciounit, preciototal;
        int cantidadCalzados;
        //seleccionada la marca
        if (jMarca.getSelectedIndex() == 1) {
            if (jRHombre.isSelected() == true) {
                //seleccionada las tallas
                if (jCTalla.getSelectedIndex() > 0 && jCTalla.getSelectedIndex() <= 5) {
                    descuento = 0.04;
                } else if (jCTalla.getSelectedIndex() == 2) {
                    descuento = 0.06;
                } else if (jCTalla.getSelectedIndex() == 3) {
                    descuento = 0.08;
                } else if (jCTalla.getSelectedIndex() == 4) {
                    descuento = 0.10;
                } else if (jCTalla.getSelectedIndex() == 5) {
                    descuento = 0.12;
                }
            }
            cantidadCalzados = (int) jCantidad.getValue();
            preciounit = Double.parseDouble(jTextPrecioU.getText());
            preciototal = (cantidadCalzados * preciounit) - ((cantidadCalzados * preciounit) * descuento);
            jTextPrecioTotal.setText(String.valueOf(preciototal));

        } else {
            JOptionPane.showMessageDialog(null, "Talla incorrcta", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTextPrecioTotal.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPromociones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCompra = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRMujer = new javax.swing.JRadioButton();
        jRHombre = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCantidad = new javax.swing.JSpinner();
        jMarca = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jTextColor = new javax.swing.JTextField();
        jTextPrecioU = new javax.swing.JTextField();
        jCTalla = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jBGenerarCompra = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextPrecioTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaDetalle = new javax.swing.JTable();
        jBLimpiarTabla = new javax.swing.JButton();
        jBQuitarCompra = new javax.swing.JButton();
        jBTotalaPagar = new javax.swing.JButton();
        jTextTotalaPagar = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setText("CALZADO RELSB");

        jPromociones.setBorder(javax.swing.BorderFactory.createTitledBorder("Promociones"));

        jLabel2.setText("Tallas Nike");

        jLabel3.setText("HOMBRES");

        jLabel4.setText("8 ->0.05% ; 8,5->0.07% ; 9 ->0.09% ;9,55 -> 0,11% ;10-> 0,13%");

        jLabel5.setText("6 ->0.04% ;68,5->0.06% ; 7 ->0.08% ;7,5 -> 0,11% ;10-> 0,13%");

        jLabel6.setText("Mujeres");

        jLabel7.setText("Tallas Adidas");

        jLabel8.setText("HOMBRES");

        jLabel9.setText("8 ->0.07% ; 8,5->0.09% ; 9 ->0.11% ;9,5 -> 0,13% ;10-> 0,15%");

        jLabel10.setText("Mujeres");

        jLabel11.setText("6 ->0.06% ;68,5->0.08% ; 7 ->0.10% ;7,5 -> 0,12% ;10-> 0,14%");

        javax.swing.GroupLayout jPromocionesLayout = new javax.swing.GroupLayout(jPromociones);
        jPromociones.setLayout(jPromocionesLayout);
        jPromocionesLayout.setHorizontalGroup(
            jPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPromocionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPromocionesLayout.createSequentialGroup()
                        .addGroup(jPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addGroup(jPromocionesLayout.createSequentialGroup()
                .addGroup(jPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPromocionesLayout.setVerticalGroup(
            jPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPromocionesLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Compra"));

        jLabel12.setText("MARCA");

        jLabel13.setText("GENERO");

        jLabel18.setText("TALLA");

        buttonGroup1.add(jRMujer);
        jRMujer.setText("MUJER");
        jRMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMujerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRHombre);
        jRHombre.setText("HOMBRE");
        jRHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRHombreActionPerformed(evt);
            }
        });

        jLabel14.setText("COLOR");

        jLabel15.setText("CANTIDAD");

        jCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));

        jMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "NIKE", "ADIDAS", " " }));
        jMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarcaActionPerformed(evt);
            }
        });

        jLabel16.setText("PRECIO UNITARIO");

        jTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextColorActionPerformed(evt);
            }
        });

        jTextPrecioU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioUActionPerformed(evt);
            }
        });

        jCTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "6", "6,5", "7", "7,5", "8", "8,5", "9", "9,5", "10", " " }));
        jCTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTallaActionPerformed(evt);
            }
        });

        jBGenerarCompra.setText("GENERAR COMPRA");
        jBGenerarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarCompraActionPerformed(evt);
            }
        });

        jBLimpiar.setText("LIMPIAR");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jLabel17.setText("PRECIO TOTAL");

        jTextPrecioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCompraLayout = new javax.swing.GroupLayout(jCompra);
        jCompra.setLayout(jCompraLayout);
        jCompraLayout.setHorizontalGroup(
            jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCompraLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCompraLayout.createSequentialGroup()
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCompraLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(109, 109, 109))
                    .addGroup(jCompraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jRHombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRMujer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCompraLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCompraLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
            .addGroup(jCompraLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jBGenerarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jCompraLayout.setVerticalGroup(
            jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCompraLayout.createSequentialGroup()
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18))
                .addGap(1, 1, 1)
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRHombre)
                    .addComponent(jRMujer)
                    .addComponent(jMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBGenerarCompra)
                        .addComponent(jBLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Compra "));

        jTablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTablaDetalle);

        jBLimpiarTabla.setText("Limpiar Tabla");
        jBLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarTablaActionPerformed(evt);
            }
        });

        jBQuitarCompra.setText("Quitar Compra");
        jBQuitarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitarCompraActionPerformed(evt);
            }
        });

        jBTotalaPagar.setText("TOTAL A PAGAR");
        jBTotalaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTotalaPagarActionPerformed(evt);
            }
        });

        jTextTotalaPagar.setBackground(new java.awt.Color(204, 204, 204));
        jTextTotalaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalaPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBLimpiarTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBQuitarCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBTotalaPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTotalaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLimpiarTabla)
                    .addComponent(jBQuitarCompra)
                    .addComponent(jBTotalaPagar)
                    .addComponent(jTextTotalaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPromociones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPrecioUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecioUActionPerformed

    private void jTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextColorActionPerformed

    private void jTextTotalaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalaPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalaPagarActionPerformed

    private void jRHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRHombreActionPerformed

    private void jRMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRMujerActionPerformed

    private void jMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMarcaActionPerformed

    private void jCTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTallaActionPerformed

    private void jBGenerarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarCompraActionPerformed
        // TODO add your handling code here:
        //GENERAR COMPRA
        if (jMarca.getSelectedIndex() != 0 && (jRHombre.isSelected() != false || jRMujer.isSelected() != false) && (!jTextColor.getText().equals("")) && (int) jCantidad.getValue() != 0 && (!jTextPrecioU.getText().equals(""))) {

            if (jRHombre.isSelected()) {
                promocionHombreNike();
                if (jCTalla.getSelectedIndex() >= 5) {
                    modelo.addRow(new Object[]{
                        jMarca.getSelectedItem(),
                        "HOMBRE",
                        jCTalla.getSelectedItem(),
                        jTextColor.getText(),
                        jCantidad.getValue(),
                        jTextPrecioU.getText(),
                        jTextPrecioTotal.getText()

                    });
                }

            } else if (jRMujer.isSelected()) {
                promocionMujerNike();
                if (jCTalla.getSelectedIndex() > 0 && jCTalla.getSelectedIndex() <= 5) {
                    modelo.addRow(new Object[]{
                        jMarca.getSelectedItem(),
                        "MUJER",
                        jCTalla.getSelectedItem(),
                        jTextColor.getText(),
                        jCantidad.getValue(),
                        jTextPrecioU.getText(),
                        jTextPrecioTotal.getText()
                    });
                }

            } else {
                JOptionPane.showMessageDialog(null, "DATOS INCOMPLETOS", "ERROR", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_jBGenerarCompraActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed

        // TODO add your handling code here:
        //LIMPIAR
        jMarca.setSelectedIndex(0);
        jRHombre.setSelected(false);
        jRMujer.setSelected(false);
        jCTalla.setSelectedIndex(0);
        jTextColor.setText("");
        jCantidad.setValue(0);
        jTextPrecioU.setText("");

    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBQuitarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitarCompraActionPerformed
        // TODO add your handling code here:
        //quitar compra


    }//GEN-LAST:event_jBQuitarCompraActionPerformed

    private void jBTotalaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTotalaPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTotalaPagarActionPerformed

    private void jTextPrecioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecioTotalActionPerformed

    private void jBLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarTablaActionPerformed
        // TODO add your handling code here:
//LIMPIAR LA TABLA
        modelo.getRowCount();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            
                modelo.removeRow(i);
            

        }
    }//GEN-LAST:event_jBLimpiarTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelsB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBGenerarCompra;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBLimpiarTabla;
    private javax.swing.JButton jBQuitarCompra;
    private javax.swing.JButton jBTotalaPagar;
    private javax.swing.JComboBox<String> jCTalla;
    private javax.swing.JSpinner jCantidad;
    private javax.swing.JPanel jCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMarca;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPromociones;
    private javax.swing.JRadioButton jRHombre;
    private javax.swing.JRadioButton jRMujer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTablaDetalle;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextColor;
    private javax.swing.JTextField jTextPrecioTotal;
    private javax.swing.JTextField jTextPrecioU;
    private javax.swing.JTextField jTextTotalaPagar;
    // End of variables declaration//GEN-END:variables
}
